[project]
name = "laag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyterlab>=4.4.2",
    "jupyterlab-myst>=2.4.2",
    "manim>=0.19.0",
    "mystmd>=1.3.26",
]
